### PR TITLE
fix: title overlapping

### PR DESCRIPTION
**Pull request by tarikcoskun**
fixed the title overlapping the "see your stats" button (for small screens)

image

### CODE REVIEW

**Review by tedspare — CHANGES_REQUESTED** [review]
Clean change. What size of screen are you using? Also, could you please ensure this works on
- visitor pages eg. `sarimrmalik.localhost:3000`,
- mobile, and
- mobile visitor pages?

Thanks for finding this.

**Comment by tarikcoskun** [comment]
sorry, i didn't notice it was affecting other stuff
my screen size is 16.5", with 1366x768 resolution

i can't test the project in localhost because of supabase but i think i found the right way of doing it, let's see

**Comment by tarikcoskun** [comment]
that looks fine on my screen size, mobile and doesn't affect the bigger ones that much

**Review by tedspare — APPROVED** [review]
LGTM

Thanks for verifying, Tarık.

**Pull request merged**
